tracking_development:
  :client_id:
  :client_secret:
  :grant_type:
  :environment:

address_development:
  :client_id:
  :client_secret:
  :grant_type:
  :environment:

shipment_development:
  :client_id:
  :client_secret:
  :grant_type:
  :environment:
  :account_number:

production:
  :client_id:
  :client_secret:
  :grant_type:
  :environment:
